# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [157]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [158]:
print (np.__version__)
print(np.show_config)

2.1.3
<function show at 0x7fc3369dc720>

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

In [159]:
A = np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [160]:
A = np.zeros(10)
A[4] = 1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [161]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [162]:
vector = np.arange(10)
Reverse_vector = np.sort(vector)[::-1]
print(Reverse_vector)

[9 8 7 6 5 4 3 2 1 0]

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [163]:
A = np.arange(9)
B = A.reshape(3,3)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [164]:
array1= np.array([1,2,0,0,4,0])
indices = np.array ([0,1,2,3,4,5])
non_zero = indices[array1 > 0]
print((non_zero,))

(array([0, 1, 4]),)

### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [165]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [166]:
A = np.random.random((3, 3, 3))
print(A)

[[[0.29280939 0.61091433 0.91302739]
  [0.300115   0.24859864 0.6663921 ]
  [0.98753291 0.46827041 0.12328738]]

 [[0.91603139 0.94614353 0.27769737]
  [0.51965369 0.154745   0.01462735]
  [0.32424321 0.99089844 0.51314129]]

 [[0.87649564 0.06739575 0.28415374]
  [0.46889927 0.76177319 0.92261178]
  [0.39302376 0.92908768 0.49961201]]]

### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [167]:
A = np.random.random((10, 10))
Max = A.max()
Min = A.min()
print(Max, Min)

0.9914673999458862 0.025222518201502453

### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [168]:
vector = np.random.random(30)
Mean = vector.mean()
print(Mean)

0.45521376102011424

### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [169]:
array1 = np.ones((10, 10))
array1[1:-1, 1:-1] = 0
print(array1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [170]:
array1 = np.ones((5, 5))
print("# before \n", array1)
array1[:,[0,4]] = 0
array1[[0,4],:] = 0
print("# after \n", array1)

# before
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
# after
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [171]:
0 * np.nan
# nan은 정의되지 않은 값이기에 0을 곱해도 정의되지 않는다

nan

In [172]:
np.nan == np.nan
# nan은 정의되지 않은 값이기에 nan 자기자신과도 같다고 할 수 없다

False

In [173]:
np.inf > np.nan
# nan은 정의되지 않은 값이기에 무한대와도 비교할 수 없다

False

In [174]:
np.nan - np.nan
# 정의되지 않은 숫자끼리 계산된 값 역시 정의되지 않는다

nan

In [175]:
np.nan in set([np.nan])
# 집합은 주소를 확인하여 같은 것으로 처리한다

True

In [176]:
0.3 == 3 * 0.1
# 컴퓨터가 이진수로 계산하는 과정에서 발생한 반올림오차에 의해 달라진

False

### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [177]:
matrix = np.random.random((5,5))
normal = (matrix - matrix.mean()) / matrix.std()
print(normal)

[[-0.38551319 -0.63616468  0.32497696  1.55735672 -1.30009198]
 [ 0.58511149  0.51210116  1.45029994  0.37174798 -0.1253629 ]
 [ 0.61289858 -1.62659177  0.17325018 -0.91963222  1.23243934]
 [ 1.53660945  1.4210004  -1.18867916 -0.98612995  0.82344032]
 [-0.80372366 -1.47548199  0.2104938  -1.27612804 -0.08822675]]

### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [178]:
A = np.ones((5, 3))
B = np.ones((3, 2))
Multi = np.dot(A, B)
print(Multi)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [179]:
np.array(0) / np.array(0)
# 0을 0으로 나누는 것은 정의될 수 없어 nan이 반환된다

/tmp/ipykernel_1061/1691739912.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)

np.float64(nan)

In [180]:
np.array(0) // np.array(0)
# 위와 동일한 이유

/tmp/ipykernel_1061/1895879892.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)

np.int64(0)

In [181]:
np.array([np.nan]).astype(int).astype(float)
# nan을 정수로 변환하면 표현할 수 없는 값이라 최솟값으로 변환된다
# 다시 실수형으로 바꾸면 해당 값이 지수 표기법으로 표현된

/tmp/ipykernel_1061/690482422.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [182]:
ones = np.ones((5, 1))
row = np.arange(5)
matrix = ones * row
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [183]:
vector1 = np.random.random(10)
vector1.sort()
print(vector1)

[0.24028251 0.41229253 0.48174599 0.57729304 0.69106221 0.70257201
 0.87568342 0.91946441 0.96032279 0.99125128]

## **판다스**


### 1. Import pandas under the alias `pd`.

In [184]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [185]:
print(pd.__version__)

2.2.3

## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

In [186]:
#3~20번 문제는 아래 데이터프레임으로 진행됩니다.
#Consider the following Python dictionary data and Python list labels:

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [187]:
# 문제 풀이 전 numpy 임포트
import numpy as np

df = pd.DataFrame(data, index=labels)

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [189]:
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [190]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [191]:
df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [192]:
df.iloc[[3, 4, 8]][['animal', 'age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [193]:
df[df['visits'] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [194]:
df[df['age'].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [195]:
df[(df['animal'] == 'cat') & (df['age'] < 3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).

In [196]:
df[(df['age'] >= 2) & (df['age'] <= 4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [197]:
df.loc['f', 'age'] = 1.5

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [198]:
total_visits = df['visits'].sum()
print(total_visits)

19

### 15. Calculate the mean age for each different animal in `df`.

In [199]:
mean_age = df.groupby('animal')['age'].mean()
print(mean_age)

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [200]:
df.loc['k'] = ['dog', 5.5, 2, 'no']
print(df)
df = df.drop('k')
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    dog  5.5       2       no
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 17. Count the number of each type of animal in `df`.

In [201]:
animal_count = df['animal'].value_counts()
print(animal_count)

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [202]:
sorted_df = df.sort_values(by=['age', 'visits'], ascending=[False, True])
print(sorted_df)

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [203]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})
print(df['priority'])

a     True
b     True
c    False
d     True
e    False
f    False
g    False
h     True
i    False
j    False
Name: priority, dtype: bool

### 20. In the 'animal' column, change the 'snake' entries to 'python'.

In [204]:
df.loc[df['animal'] == 'snake', 'animal'] = 'python'

In [205]:
# 확인용 df 출력 셀
df

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [206]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))
row_mean = df.mean(axis=1)
result = df.sub(row_mean, axis=0)
print(result)

          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278