# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [4]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [5]:
print(np.__version__)
np.show_config()

2.5.3
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.3.0",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.34.106.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sp8l_b7i/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sp8l_b7i/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib",
      "openblas configuration": "OpenBLAS 0.3.34.106.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=24",
      "pc file directory": "D:/a/numpy-release/numpy-release/.openblas"
    },
    "lapack": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.34.106.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sp8l_b7i/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sp8l_b7i/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib",
      "openblas configuration": "OpenBLAS 0.3.34.106.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=24",
      "pc file directory": "D:/a/numpy-release/numpy-release/.openblas"
    }
  },
  "Python Information": {
    "path": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\build-env-mk5sjh7q\\Scripts\\python.exe",
    "version": "3.14"
  },
  "SIMD Extensions": {
    "baseline": [
      "X86_V2"
    ],
    "found": [
      "X86_V3"
    ]
  }
}

c:\Users\0510n\AppData\Local\Programs\Python\Python314\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

In [16]:
print(np.zeros((10)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [7]:
a=np.zeros((10))
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [15]:
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [14]:
a=np.arange(10)[::-1]
print(a)

[9 8 7 6 5 4 3 2 1 0]

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [17]:
print(np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [19]:
a=np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4]),)

### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [20]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [22]:
print(np.random.random((3, 3, 3)))

[[[0.90142939 0.18419336 0.55564273]
  [0.69474673 0.76521314 0.12256749]
  [0.95716661 0.24377274 0.32727178]]

 [[0.55261516 0.36244368 0.47791703]
  [0.4410188  0.71107211 0.51482288]
  [0.38049234 0.11862388 0.46213797]]

 [[0.33471108 0.7778683  0.58434581]
  [0.53614475 0.08788091 0.99796377]
  [0.56994493 0.70336269 0.02608188]]]

### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [25]:
a=np.random.random((10, 10))
print(np.min(a), np.max(a))

0.0167230756404797 0.9867858022960103

### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [26]:
a=np.random.rand(30)
print(np.mean(a))

0.6022365831597484

### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [29]:
a=np.ones((10,10))
a[1:-1, 1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [35]:
#before
a=np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [34]:
#after
a[[0, 4], :]=0
a[1:4, [0,-1]]=0
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan #nan은 결측값이기 때문에 결과를 확정할 수 없어 nan이 된다. 
np.nan == np.nan #nan은 결측값, 즉 알 수 없는 값이기 때문에 어떤 값과 비교해도 같다고 인정하지 않아 False
np.inf > np.nan #nan은 알 수 없는 값이라서 비교하면 False 
np.nan - np.nan #nan이 포함된 계산. 결측값에서 결측값을 빼면 정확한 값을 알 수 없어서 False 
np.nan in set([np.nan]) #set 내에 같은 객체를 찾을 수 있어서 True
0.3 == 3 * 0.1 #부동소수점 오차 때문에 False

nan

### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [41]:
a=np.random.random((5, 5))
print((a-np.mean(a))/np.std(a))

[[-0.64811893  0.90094298  1.02175916  1.3937618  -0.48112958]
 [ 1.00220269 -1.53188699  0.91252964 -0.04139479 -1.21054705]
 [ 0.63610963  1.35535821  1.01831974 -1.17548198 -0.55316725]
 [-1.66334574  1.5395319   0.27475804 -0.36764009  0.15457769]
 [-0.64009424  1.05572799 -1.26764723 -0.91481585 -0.77030975]]

### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [42]:
A=np.ones((5,3))
B=np.ones((3,2))
print(np.dot(A, B))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [55]:
np.array(0) / np.array(0)  # nan: 0을 0으로 나눌 수 없어 NaN이 됨
np.array(0) // np.array(0)  # 0: 0//0은 정의되지 않지만 numpy의 정수 연산에서 0으로 반환됨
np.array([np.nan]).astype(int).astype(float) # [-9.22337204e+18]: NaN을 int64로 변환할 때 int64의 최솟값으로 처리된 후 float로 변환

C:\Users\0510n\AppData\Local\Temp\ipykernel_18616\3880469154.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)  # nan: 0을 0으로 나눌 수 없어 NaN이 됨
C:\Users\0510n\AppData\Local\Temp\ipykernel_18616\3880469154.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)  # 0: 0//0은 정의되지 않지만 numpy의 정수 연산에서 0으로 반환됨
C:\Users\0510n\AppData\Local\Temp\ipykernel_18616\3880469154.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float) # [-9.22337204e+18]: NaN을 int64로 변환할 때 int64의 최솟값으로 처리된 후 float로 변환

array([-9.22337204e+18])

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [52]:
a=np.arange(5)
a=np.tile(a,(5,1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [50]:
a=np.random.rand(10)
print(np.sort(a))

[0.01191224 0.01311823 0.25353838 0.29853986 0.32467532 0.35452973
 0.50015559 0.56368914 0.60511237 0.61477766]

## **판다스**


### 1. Import pandas under the alias `pd`.

In [56]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [57]:
print(pd.__version__)

3.0.5

## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [62]:
# 문제 풀이 전 numpy 임포트
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data, index=labels)

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [63]:
print(df.info())

<class 'pandas.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     str
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 400.0+ bytes
None

### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [64]:
print(df.describe())

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [65]:
df.iloc[0:3, :]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [66]:
df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [69]:
df.iloc[[3,4,8], [0,1]]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [67]:
df[df['visits']>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [72]:
df[df['age'].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [74]:
df[(df['animal']=='cat') & (df['age'] <3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).

In [75]:
df[(df['age']>=2) & (df['age']<=4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [78]:
df.loc['f', ['age']] =1.5

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [80]:
print(df['visits'].sum())

19

### 15. Calculate the mean age for each different animal in `df`.

In [82]:
#animal 별로 평균 age 계산 
df.groupby(by=['animal'])['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [89]:
df.loc['k', :]= ['cat', 2.0, 3, 'yes']
df.drop(axis=0, index='k', inplace=True)

### 17. Count the number of each type of animal in `df`.

In [92]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [97]:
df.sort_values(by=['age', 'visits'], ascending=[False,True], inplace=True)
df

  animal  age  visits priority
i    dog  7.0     2.0       no
e    dog  5.0     2.0       no
g  snake  4.5     1.0       no
j    dog  3.0     1.0       no
b    cat  3.0     3.0      yes
a    cat  2.5     1.0      yes
f    cat  1.5     3.0       no
c  snake  0.5     2.0       no
h    cat  NaN     1.0      yes
d    dog  NaN     3.0      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [101]:
df['priority'] = df['priority'].map(lambda x: True if x == 'yes' else False)
df

  animal  age  visits  priority
i    dog  7.0     2.0     False
e    dog  5.0     2.0     False
g  snake  4.5     1.0     False
j    dog  3.0     1.0     False
b    cat  3.0     3.0     False
a    cat  2.5     1.0     False
f    cat  1.5     3.0     False
c  snake  0.5     2.0     False
h    cat  NaN     1.0     False
d    dog  NaN     3.0     False

### 20. In the 'animal' column, change the 'snake' entries to 'python'.

In [102]:
df['animal']=df['animal'].apply(lambda x: 'python' if x=='snake' else x)

In [103]:
# 확인용 df 출력 셀
df

   animal  age  visits  priority
i     dog  7.0     2.0     False
e     dog  5.0     2.0     False
g  python  4.5     1.0     False
j     dog  3.0     1.0     False
b     cat  3.0     3.0     False
a     cat  2.5     1.0     False
f     cat  1.5     3.0     False
c  python  0.5     2.0     False
h     cat  NaN     1.0     False
d     dog  NaN     3.0     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [111]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))

In [112]:
df=df.sub(df.mean(axis=1) , axis=0)
df

          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278